# The backend tells Decap CMS where your code is stored.
backend:
  name: github
  repo: idosom/quick
  branch: main
  base_url: https://github.com 
  auth_scope: repo
  client_id: Ov23li7CouZziaW3n7qR

# This tells the CMS where to store images, if you add them.
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# This is the "collection," or the data file we want to edit.
# This is the "collection," or the data file we want to edit.
collections:
  - name: "bookmarks" 
    label: "Bookmarks"
    label_singular: "Bookmark"
    folder: "/"
    file: "bookmarks.json"
    format: "json"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "URL"
        name: "url"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"